copyright: Copyright © Arthri 2022
site_author: Arthri

site_name: Belp
site_description: A collection of build tools and extensions.

repo_url: https://github.com/Arthri/Belp
site_url: https://arthri.github.io/Belp



nav:
  - Home: index.md
  - Contributing.md



markdown_extensions:
  abbr: {}
  admonition: {}
  attr_list: {}
  def_list: {}
  footnotes: {}
  md_in_html: {}
  nl2br: {}
  sane_lists: {}
  smarty: {}
  tables: {}
  toc:
    permalink: true

  pymdownx.betterem: {}
  pymdownx.caret: {}
  pymdownx.critic: {}
  pymdownx.details: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.highlight:
    anchor_linenums: true
    auto_title: true
    linenums: true
  pymdownx.inlinehilite: {}
  pymdownx.keys: {}
  pymdownx.magiclink: {}
  pymdownx.mark: {}
  pymdownx.progressbar: {}
  pymdownx.saneheaders: {}
  pymdownx.smartsymbols: {}
  pymdownx.snippets:
    check_paths: true
  pymdownx.superfences: {}
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.tasklist:
    custom_checkbox: true
  pymdownx.tilde: {}



plugins:
  git-revision-date-localized:
    enabled: !ENV [CI, false]
    enable_creation_date: true
    type: datetime
  minify:
    minify_html: true
  search: {}
  social:
    cards: !ENV [CI, false]
  tags:
    enabled: !ENV [CI, false]
    tags_allowed: {}



theme:
  name: material

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: amber
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      media: "(prefers-color-scheme: dark)"
    - scheme: default
      primary: yellow
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      media: "(prefers-color-scheme: light)"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Arthri/Belp
